services:
  position-api:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=5001
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    expose:
      - "5001"
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    shm_size: "1gb"
